id: P009102
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-19 19:23:01.428669
source_metadata:
  id: bdr:W22008
  title: སུམ་རྟགས་གཉིས་ཀྱི་ཚིག་དོན་མདོར་བསྡུས།
  author: ''
  volumes:
    fc62cf2cc3834446a3519569d19da30a:
      image_group_id: I1KG14887
      title: ''
      volume_number: 1
      total_pages: 44
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
