id: ID81132DA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T22:16:17+00:00'
last_modified: '2022-06-08T08:37:53.523110+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22008
  title: སུམ་རྟགས་གཉིས་ཀྱི་ཚིག་དོན་མདོར་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    03B6:
      image_group_id: I1KG14887
      title: ''
      total_pages: 44
      order: 1
      base_file: 03B6.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
